<a href="https://colab.research.google.com/github/edusantos-tech/eduardo-miguel-dos-santos/blob/main/AT_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import statistics
import random
import numpy as np

In [2]:

def calcula_imc(peso=70, altura=1.75):
    return peso / (altura ** 2)

imc = calcula_imc()
print(f"IMC calculado: {imc:.2f}")


IMC calculado: 22.86


In [3]:
alturas = [45, 23, 67, 12, 11, 89, 23, 41, 50, 62, 78, 34, 56, 19, 72, 88, 11, 90,
           39, 65, 76, 27, 48, 59, 81, 14, 11, 93, 3, 68, 29, 52, 74, 16, 85, 20,
           55, 38, 69, 11, 83, 7, 44, 61, 18, 96, 22, 58, 31, 71, 40, 53, 87, 31]

print(f"Maior valor: {max(alturas)}")
print(f"Menor valor: {min(alturas)}")
print(f"Soma dos valores: {sum(alturas)}")
print(f"Valor absoluto de -25: {abs(-25)}")
print(f"Arredondamento de 3.14159 para 2 casas decimais: {round(3.14159, 2)}")
print(f"Média: {statistics.mean(alturas)}")
print(f"Mediana: {statistics.median(alturas)}")
print(f"Moda: {statistics.mode(alturas)}")
print(f"Variância amostral: {statistics.variance(alturas)}")
print(f"Desvio padrão amostral: {statistics.stdev(alturas)}")

Maior valor: 96
Menor valor: 3
Soma dos valores: 2606
Valor absoluto de -25: 25
Arredondamento de 3.14159 para 2 casas decimais: 3.14
Média: 48.25925925925926
Mediana: 49.0
Moda: 11
Variância amostral: 741.1013277428372
Desvio padrão amostral: 27.223176297831913


In [4]:
matriz_float = np.random.rand(5, 10)
print("\nMatriz 5x10 de floats entre 0 e 1:")
print(matriz_float)
matriz_int = np.random.randint(0, 10, size=(8, 4))
print("\nMatriz 8x4 de inteiros entre 0 e 9:")
print(matriz_int)


Matriz 5x10 de floats entre 0 e 1:
[[0.81915347 0.01577666 0.49238058 0.97118184 0.70692631 0.0324586
  0.36902489 0.04235618 0.51955595 0.56468299]
 [0.54498351 0.74366125 0.79224511 0.71451637 0.8026057  0.38325591
  0.60347317 0.04119339 0.70564472 0.10633745]
 [0.00332346 0.37299807 0.72486703 0.71479147 0.28479159 0.48396624
  0.69410808 0.73297432 0.18811613 0.05843345]
 [0.88555062 0.59394687 0.269711   0.49220292 0.23195961 0.87499787
  0.22017552 0.27349202 0.60845104 0.86339604]
 [0.51382307 0.0372604  0.36164538 0.0524914  0.31593126 0.34410672
  0.85277678 0.6364071  0.73635688 0.15604349]]

Matriz 8x4 de inteiros entre 0 e 9:
[[7 9 4 5]
 [6 2 2 5]
 [2 1 0 3]
 [2 4 4 1]
 [8 7 0 1]
 [0 7 3 4]
 [9 2 1 2]
 [6 8 9 3]]
