<a href="https://colab.research.google.com/github/edusantos-tech/eduardo-miguel-dos-santos/blob/main/at_05(_listas_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nova seção

In [ ]:
import statistics
import random
import numpy as np

def calcula_imc(peso=70, altura=1.75):
    return peso / (altura ** 2)

alturas = [
    45, 23, 67, 12, 11, 89, 23, 41, 50, 62, 78, 34, 56, 19, 72, 88,
    11, 90, 39, 65, 76, 27, 48, 59, 81, 14, 11, 93, 3, 68, 29, 52,
    74, 16, 85, 20, 55, 38, 69, 11, 83, 7, 44, 61, 18, 96, 22, 58,
    31, 71, 40, 53, 87, 31
]

print("Maior valor:", max(alturas))
print("Menor valor:", min(alturas))
print("Soma total:", sum(alturas))
print("Valor absoluto de -25:", abs(-25))
print("Arredondamento de 3.14159:", round(3.14159, 2))
print("Média:", statistics.mean(alturas))
print("Mediana:", statistics.median(alturas))
print("Moda:", statistics.mode(alturas))
print("Variância:", statistics.variance(alturas))
print("Desvio padrão:", statistics.stdev(alturas))

matriz_float = np.random.rand(5, 10)
matriz_int = np.random.randint(0, 10, (8, 4))

print("\nMatriz 5x10 de floats aleatórios:")
print(matriz_float)

print("\nMatriz 8x4 de inteiros aleatórios:")
print(matriz_int)


Maior valor: 96
Menor valor: 3
Soma total: 2606
Valor absoluto de -25: 25
Arredondamento de 3.14159: 3.14
Média: 48.25925925925926
Mediana: 49.0
Moda: 11
Variância: 741.1013277428372
Desvio padrão: 27.223176297831913

Matriz 5x10 de floats aleatórios:
[[0.091024   0.96516456 0.87018273 0.26052215 0.87240774 0.98671568
  0.73611969 0.10213904 0.35256157 0.83080121]
 [0.38959948 0.66991264 0.42628931 0.83434944 0.16207952 0.61835456
  0.87437557 0.88333623 0.67029602 0.04568708]
 [0.72987683 0.78345142 0.86114931 0.80989024 0.90006482 0.83242074
  0.06469177 0.84171321 0.76843005 0.24034886]
 [0.62386129 0.36516323 0.65333521 0.74291949 0.11290193 0.55040733
  0.77312686 0.20600766 0.41870166 0.63934388]
 [0.05500964 0.38879801 0.32806141 0.49140789 0.80710283 0.13994388
  0.80834895 0.98365198 0.51530858 0.25622689]]

Matriz 8x4 de inteiros aleatórios:
[[1 2 2 9]
 [9 2 9 1]
 [0 1 5 3]
 [6 3 7 1]
 [8 9 8 1]
 [5 3 4 2]
 [1 8 5 2]
 [5 9 1 2]]
