<a href="https://colab.research.google.com/github/edusantos-tech/eduardo-miguel-dos-santos/blob/main/at_05(dicionarios).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Função para gerar matrizes aleatórias
def gerar_matrizes():
    return {
        "Matriz 5x10 de floats (0 a 1)": np.random.rand(5, 10),
        "Matriz 8x4 de inteiros (0 a 9)": np.random.randint(0, 10, (8, 4))
    }

# Exibir matrizes
matrizes = gerar_matrizes()
for chave, matriz in matrizes.items():
    print(f"{chave}:\n{matriz}\n")


Matriz 5x10 de floats (0 a 1):
[[0.4018684  0.82166608 0.84615905 0.33595118 0.23714883 0.4693411
  0.01317192 0.11264473 0.52292308 0.31389969]
 [0.60107741 0.53114147 0.89734987 0.46093484 0.66052235 0.55880637
  0.1520517  0.94664913 0.56229445 0.02371865]
 [0.11555735 0.08226617 0.10784164 0.88690988 0.53117449 0.91672846
  0.50007546 0.02693904 0.64350095 0.8434367 ]
 [0.33618982 0.71515254 0.078797   0.21128764 0.46331349 0.42723118
  0.55608346 0.86743312 0.11455095 0.0543199 ]
 [0.60242098 0.52997948 0.99185285 0.39422051 0.79876647 0.53018067
  0.02587292 0.58072936 0.60029812 0.77032979]]

Matriz 8x4 de inteiros (0 a 9):
[[0 7 4 4]
 [0 4 4 6]
 [7 1 0 2]
 [1 6 2 8]
 [7 7 6 2]
 [7 4 0 0]
 [7 5 6 0]
 [2 7 6 0]]

